const STUDENT_SITES= {
"Andrea"    : "https://amartinez-69.github.io/CSC209/startPage.html", 
"Andrew"    : "#", 
"Bintu"     : "https://bjalloh910.github.io/CSC209/startPage.html", 
"Chris"     : "https://wu-chris.github.io/CSC209/startPage.html", 
"Erin"      : "https://eelizabethriley.github.io/CSC209/startPage.html", 
"Hillary"   : "https://hillarydunkley16.github.io/CSC209_Class/CSC209/startPage.html", 
"Jade"      : "https://gemstone496.github.io/CSC209/start_page.html",
"Karen"     : "https://kvg-png.github.io/CSC209/CSC209/startPage.html", 
"Katie"     : "https://kat1ev.github.io/209/Weeks/Week1/homePage.html", 
"Matheus"   : "https://mcdasilva.github.io/CSC209/StartPage/startPage.html", 
"Michelle"  : "https://lawsonm525.github.io/startPage.html",
"Mikayle"   : "https://mikayledesp.github.io/CSC209/startPage.html", 
"Rachael A"  : "https://rachaelan1.github.io/CSC209/startPage.html", 
"Rachel K"  : "https://rkunkel05.github.io/CSC209/startPage.html", 
"Sophia"    : "#", 
"Susie"     : "https://susieh33.github.io/CSC209/startPage.html", 
"Yijing"    : "https://yijingyin.github.io/CSC209/startPage.html", 
"Yuzhang"   : "https://yuzfu.github.io/CSC209/startPage.html", 
"Lynne"     : "https://lynnelzr.github.io/CSC209/startPage.html", 
"Zihan"     : "https://zihanlyu.github.io/CSC209/startPage.html"
}